-libraryjars C:\Program Files\WTK2.5.2_01\lib\midpapi20.jar;C:\Program Files\WTK2.5.2_01\lib\wma11.jar;C:\Program Files\WTK2.5.2_01\lib\cldcapi10.jar
-injars C:\Documents and Settings\Administrator\j2mewtk\2.5.2\apps\AC lite\bin\AC lite.jar
-outjar C:\DOCUME~1\ADMINI~1\LOCALS~1\Temp\AC lite.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
-dontusemixedcaseclassnames
